import type { KeyboardLayoutDefinition } from '../types'

/**
 * German Neo 2 reference profile.
 *
 * Provenance:
 * - First-party Neo 2 documentation: neo-layout.org / dl.neo-layout.org
 * - Machine-readable xkeyboard-config: symbols/de xkb_symbols "neo_base" & "neo"
 * - Inclusions:
 *     shift(both_capslock)
 *     level3(caps_switch), level3(bksl_switch)
 *     level5(lsgt_switch_lock), level5(ralt_switch_lock)
 *
 * Note on XKB Level mapping:
 * - XKB Level 1 -> Neo Layer 1 (Base)
 * - XKB Level 2 -> Neo Layer 2 (Shift)
 * - XKB Level 3 -> Neo Layer 3 (Neo Mod3)
 * - XKB Level 4 -> Neo Layer 5 (Shift + Neo Mod3)
 * - XKB Level 5 -> Neo Layer 4 (Neo Mod4: navigation & keypad)
 * - XKB Level 7 -> Neo Layer 6 (Neo Mod3 + Neo Mod4: math / symbols)
 *
 * Neo Mod3 activators: CapsLock, Backslash (<BKSL>)
 * Neo Mod4 activators: IntlBackslash (<LSGT>), AltRight (<RALT>)
 * (Note: ANSI keyboards may lack physical IntlBackslash / <LSGT>).
 */
export const DE_NEO2_LAYOUT: KeyboardLayoutDefinition = {
  id: 'de-neo2',
  displayName: 'German Neo 2',
  description: 'Ergonomic German keyboard layout with 6 distinct semantic layers.',
  provenance: 'neo-layout.org & xkeyboard-config symbols/de neo_base',
  modifierActivators: [
    {
      modifier: 'shift',
      physicalKeys: ['ShiftLeft', 'ShiftRight'],
      description: 'Shift (Layer 2 / uppercase)',
    },
    {
      modifier: 'mod3',
      physicalKeys: ['CapsLock', 'Backslash'],
      description: 'Neo Mod3 (Layer 3 & 5 & 6)',
    },
    {
      modifier: 'mod4',
      physicalKeys: ['IntlBackslash', 'AltRight'],
      description: 'Neo Mod4 (Layer 4 navigation/keypad & Layer 6)',
    },
  ],
  layers: [
    {
      layerNumber: 1,
      name: 'Layer 1',
      description: 'Base lowercase alphanumeric layer',
      modifiersDescription: 'None',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'dead-key', deadKeyId: 'circumflex', displayLabel: '^' },
        Digit1: { type: 'text', output: '1' },
        Digit2: { type: 'text', output: '2' },
        Digit3: { type: 'text', output: '3' },
        Digit4: { type: 'text', output: '4' },
        Digit5: { type: 'text', output: '5' },
        Digit6: { type: 'text', output: '6' },
        Digit7: { type: 'text', output: '7' },
        Digit8: { type: 'text', output: '8' },
        Digit9: { type: 'text', output: '9' },
        Digit0: { type: 'text', output: '0' },
        Minus: { type: 'text', output: '-' },
        Equal: { type: 'dead-key', deadKeyId: 'grave', displayLabel: '`' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        KeyQ: { type: 'text', output: 'x' },
        KeyW: { type: 'text', output: 'v' },
        KeyE: { type: 'text', output: 'l' },
        KeyR: { type: 'text', output: 'c' },
        KeyT: { type: 'text', output: 'w' },
        KeyY: { type: 'text', output: 'k' },
        KeyU: { type: 'text', output: 'h' },
        KeyI: { type: 'text', output: 'g' },
        KeyO: { type: 'text', output: 'f' },
        KeyP: { type: 'text', output: 'q' },
        BracketLeft: { type: 'text', output: 'ß' },
        BracketRight: { type: 'dead-key', deadKeyId: 'acute', displayLabel: '´' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'text', output: 'u' },
        KeyS: { type: 'text', output: 'i' },
        KeyD: { type: 'text', output: 'a' },
        KeyF: { type: 'text', output: 'e' },
        KeyG: { type: 'text', output: 'o' },
        KeyH: { type: 'text', output: 's' },
        KeyJ: { type: 'text', output: 'n' },
        KeyK: { type: 'text', output: 'r' },
        KeyL: { type: 'text', output: 't' },
        Semicolon: { type: 'text', output: 'd' },
        Quote: { type: 'text', output: 'y' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'text', output: 'ü' },
        KeyX: { type: 'text', output: 'ö' },
        KeyC: { type: 'text', output: 'ä' },
        KeyV: { type: 'text', output: 'p' },
        KeyB: { type: 'text', output: 'z' },
        KeyN: { type: 'text', output: 'b' },
        KeyM: { type: 'text', output: 'm' },
        Comma: { type: 'text', output: ',' },
        Period: { type: 'text', output: '.' },
        Slash: { type: 'text', output: 'j' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 2,
      name: 'Layer 2',
      description: 'Uppercase letters and shifted typographic symbols',
      modifiersDescription: 'Shift',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'dead-key', deadKeyId: 'caron', displayLabel: 'ˇ' },
        Digit1: { type: 'text', output: '°' },
        Digit2: { type: 'text', output: '§' },
        Digit3: { type: 'text', output: 'ℓ' },
        Digit4: { type: 'text', output: '»' },
        Digit5: { type: 'text', output: '«' },
        Digit6: { type: 'text', output: '$' },
        Digit7: { type: 'text', output: '€' },
        Digit8: { type: 'text', output: '„' },
        Digit9: { type: 'text', output: '“' },
        Digit0: { type: 'text', output: '”' },
        Minus: { type: 'text', output: '—' },
        Equal: { type: 'dead-key', deadKeyId: 'cedilla', displayLabel: '¸' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'tab', displayLabel: 'ISO Left Tab' },
        KeyQ: { type: 'text', output: 'X' },
        KeyW: { type: 'text', output: 'V' },
        KeyE: { type: 'text', output: 'L' },
        KeyR: { type: 'text', output: 'C' },
        KeyT: { type: 'text', output: 'W' },
        KeyY: { type: 'text', output: 'K' },
        KeyU: { type: 'text', output: 'H' },
        KeyI: { type: 'text', output: 'G' },
        KeyO: { type: 'text', output: 'F' },
        KeyP: { type: 'text', output: 'Q' },
        BracketLeft: { type: 'text', output: 'ẞ' },
        BracketRight: { type: 'dead-key', deadKeyId: 'tilde', displayLabel: '~' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'text', output: 'U' },
        KeyS: { type: 'text', output: 'I' },
        KeyD: { type: 'text', output: 'A' },
        KeyF: { type: 'text', output: 'E' },
        KeyG: { type: 'text', output: 'O' },
        KeyH: { type: 'text', output: 'S' },
        KeyJ: { type: 'text', output: 'N' },
        KeyK: { type: 'text', output: 'R' },
        KeyL: { type: 'text', output: 'T' },
        Semicolon: { type: 'text', output: 'D' },
        Quote: { type: 'text', output: 'Y' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'text', output: 'Ü' },
        KeyX: { type: 'text', output: 'Ö' },
        KeyC: { type: 'text', output: 'Ä' },
        KeyV: { type: 'text', output: 'P' },
        KeyB: { type: 'text', output: 'Z' },
        KeyN: { type: 'text', output: 'B' },
        KeyM: { type: 'text', output: 'M' },
        Comma: { type: 'text', output: '–' },
        Period: { type: 'text', output: '•' },
        Slash: { type: 'text', output: 'J' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 3,
      name: 'Layer 3',
      description: 'Programming and special characters',
      modifiersDescription: 'Neo Mod3',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'text', output: '↻' },
        Digit1: { type: 'text', output: '¹' },
        Digit2: { type: 'text', output: '²' },
        Digit3: { type: 'text', output: '³' },
        Digit4: { type: 'text', output: '›' },
        Digit5: { type: 'text', output: '‹' },
        Digit6: { type: 'text', output: '¢' },
        Digit7: { type: 'text', output: '¥' },
        Digit8: { type: 'text', output: '‚' },
        Digit9: { type: 'text', output: '‘' },
        Digit0: { type: 'text', output: '’' },
        Minus: { type: 'unmapped' },
        Equal: { type: 'dead-key', deadKeyId: 'ring-above', displayLabel: '˚' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'compose', displayLabel: 'Compose' },
        KeyQ: { type: 'text', output: '…' },
        KeyW: { type: 'text', output: '_' },
        KeyE: { type: 'text', output: '[' },
        KeyR: { type: 'text', output: ']' },
        KeyT: { type: 'text', output: '^' },
        KeyY: { type: 'text', output: '!' },
        KeyU: { type: 'text', output: '<' },
        KeyI: { type: 'text', output: '>' },
        KeyO: { type: 'text', output: '=' },
        KeyP: { type: 'text', output: '&' },
        BracketLeft: { type: 'text', output: 'ſ' },
        BracketRight: { type: 'dead-key', deadKeyId: 'stroke', displayLabel: '/' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'text', output: '\\' },
        KeyS: { type: 'text', output: '/' },
        KeyD: { type: 'text', output: '{' },
        KeyF: { type: 'text', output: '}' },
        KeyG: { type: 'text', output: '*' },
        KeyH: { type: 'text', output: '?' },
        KeyJ: { type: 'text', output: '(' },
        KeyK: { type: 'text', output: ')' },
        KeyL: { type: 'text', output: '-' },
        Semicolon: { type: 'text', output: ':' },
        Quote: { type: 'text', output: '@' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'text', output: '#' },
        KeyX: { type: 'text', output: '$' },
        KeyC: { type: 'text', output: '|' },
        KeyV: { type: 'text', output: '~' },
        KeyB: { type: 'text', output: '`' },
        KeyN: { type: 'text', output: '+' },
        KeyM: { type: 'text', output: '%' },
        Comma: { type: 'text', output: '"' },
        Period: { type: 'text', output: "'" },
        Slash: { type: 'text', output: ';' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 4,
      name: 'Layer 4',
      description: 'Navigation block and embedded numeric keypad (derived from XKB Level 5)',
      modifiersDescription: 'Neo Mod4',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'dead-key', deadKeyId: 'dot-above', displayLabel: '˙' },
        Digit1: { type: 'text', output: 'ª' },
        Digit2: { type: 'text', output: 'º' },
        Digit3: { type: 'text', output: '№' },
        Digit4: { type: 'unmapped' },
        Digit5: { type: 'text', output: '·' },
        Digit6: { type: 'text', output: '£' },
        Digit7: { type: 'text', output: '¤' },
        Digit8: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        Digit9: { type: 'keypad', keypadKey: 'kp-divide', displayLabel: 'KP ÷' },
        Digit0: { type: 'keypad', keypadKey: 'kp-multiply', displayLabel: 'KP ×' },
        Minus: { type: 'keypad', keypadKey: 'kp-subtract', displayLabel: 'KP −' },
        Equal: { type: 'dead-key', deadKeyId: 'diaeresis', displayLabel: '¨' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'unmapped' },
        KeyQ: { type: 'action', action: 'page-up', displayLabel: 'Page Up' },
        KeyW: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },
        KeyE: { type: 'action', action: 'arrow-up', displayLabel: 'Up' },
        KeyR: { type: 'action', action: 'delete', displayLabel: 'Delete' },
        KeyT: { type: 'action', action: 'page-down', displayLabel: 'Page Down' },
        KeyY: { type: 'text', output: '¡' },
        KeyU: { type: 'keypad', keypadKey: 'kp-7', displayLabel: 'KP 7' },
        KeyI: { type: 'keypad', keypadKey: 'kp-8', displayLabel: 'KP 8' },
        KeyO: { type: 'keypad', keypadKey: 'kp-9', displayLabel: 'KP 9' },
        KeyP: { type: 'keypad', keypadKey: 'kp-add', displayLabel: 'KP +' },
        BracketLeft: { type: 'text', output: '−' },
        BracketRight: { type: 'dead-key', deadKeyId: 'double-acute', displayLabel: '˝' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'action', action: 'home', displayLabel: 'Home' },
        KeyS: { type: 'action', action: 'arrow-left', displayLabel: 'Left' },
        KeyD: { type: 'action', action: 'arrow-down', displayLabel: 'Down' },
        KeyF: { type: 'action', action: 'arrow-right', displayLabel: 'Right' },
        KeyG: { type: 'action', action: 'end', displayLabel: 'End' },
        KeyH: { type: 'text', output: '¿' },
        KeyJ: { type: 'keypad', keypadKey: 'kp-4', displayLabel: 'KP 4' },
        KeyK: { type: 'keypad', keypadKey: 'kp-5', displayLabel: 'KP 5' },
        KeyL: { type: 'keypad', keypadKey: 'kp-6', displayLabel: 'KP 6' },
        Semicolon: { type: 'keypad', keypadKey: 'kp-separator', displayLabel: 'KP ,' },
        Quote: { type: 'text', output: '.' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'action', action: 'escape', displayLabel: 'Escape' },
        KeyX: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        KeyC: { type: 'action', action: 'insert', displayLabel: 'Insert' },
        KeyV: { type: 'action', action: 'enter', displayLabel: 'Return' },
        KeyB: { type: 'action', action: 'undo', displayLabel: 'Undo' },
        KeyN: { type: 'text', output: ':' },
        KeyM: { type: 'keypad', keypadKey: 'kp-1', displayLabel: 'KP 1' },
        Comma: { type: 'keypad', keypadKey: 'kp-2', displayLabel: 'KP 2' },
        Period: { type: 'keypad', keypadKey: 'kp-3', displayLabel: 'KP 3' },
        Slash: { type: 'text', output: ';' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'keypad', keypadKey: 'kp-0', displayLabel: 'KP 0' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 5,
      name: 'Layer 5',
      description: 'Greek lowercase and subscripts (derived from XKB Level 4)',
      modifiersDescription: 'Shift + Neo Mod3',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'text', output: '˞' },
        Digit1: { type: 'text', output: '₁' },
        Digit2: { type: 'text', output: '₂' },
        Digit3: { type: 'text', output: '₃' },
        Digit4: { type: 'text', output: '♀' },
        Digit5: { type: 'text', output: '♂' },
        Digit6: { type: 'text', output: '⚥' },
        Digit7: { type: 'text', output: 'ϰ' },
        Digit8: { type: 'text', output: '⟨' },
        Digit9: { type: 'text', output: '⟩' },
        Digit0: { type: 'text', output: '₀' },
        Minus: { type: 'text', output: '‑' },
        Equal: { type: 'dead-key', deadKeyId: 'dasia', displayLabel: '῾' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'unmapped' },
        KeyQ: { type: 'text', output: 'ξ' },
        KeyW: { type: 'unmapped' },
        KeyE: { type: 'text', output: 'λ' },
        KeyR: { type: 'text', output: 'χ' },
        KeyT: { type: 'text', output: 'ω' },
        KeyY: { type: 'text', output: 'κ' },
        KeyU: { type: 'text', output: 'ψ' },
        KeyI: { type: 'text', output: 'γ' },
        KeyO: { type: 'text', output: 'φ' },
        KeyP: { type: 'text', output: 'ϕ' },
        BracketLeft: { type: 'text', output: 'ς' },
        BracketRight: { type: 'dead-key', deadKeyId: 'psili', displayLabel: '᾿' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'unmapped' },
        KeyS: { type: 'text', output: 'ι' },
        KeyD: { type: 'text', output: 'α' },
        KeyF: { type: 'text', output: 'ε' },
        KeyG: { type: 'text', output: 'ο' },
        KeyH: { type: 'text', output: 'σ' },
        KeyJ: { type: 'text', output: 'ν' },
        KeyK: { type: 'text', output: 'ρ' },
        KeyL: { type: 'text', output: 'τ' },
        Semicolon: { type: 'text', output: 'δ' },
        Quote: { type: 'text', output: 'υ' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'unmapped' },
        KeyX: { type: 'text', output: 'ϵ' },
        KeyC: { type: 'text', output: 'η' },
        KeyV: { type: 'text', output: 'π' },
        KeyB: { type: 'text', output: 'ζ' },
        KeyN: { type: 'text', output: 'β' },
        KeyM: { type: 'text', output: 'μ' },
        Comma: { type: 'text', output: 'ϱ' },
        Period: { type: 'text', output: 'ϑ' },
        Slash: { type: 'text', output: 'θ' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'No-Break Space' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 6,
      name: 'Layer 6',
      description: 'Mathematical symbols and Greek uppercase (derived from XKB Level 7)',
      modifiersDescription: 'Neo Mod3 + Neo Mod4',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'dead-key', deadKeyId: 'dot-below', displayLabel: '̣' },
        Digit1: { type: 'text', output: '¬' },
        Digit2: { type: 'text', output: '∨' },
        Digit3: { type: 'text', output: '∧' },
        Digit4: { type: 'text', output: '⊥' },
        Digit5: { type: 'text', output: '∡' },
        Digit6: { type: 'text', output: '∥' },
        Digit7: { type: 'text', output: '→' },
        Digit8: { type: 'text', output: '∞' },
        Digit9: { type: 'text', output: '∝' },
        Digit0: { type: 'text', output: '∅' },
        Minus: { type: 'text', output: '‐' },
        Equal: { type: 'dead-key', deadKeyId: 'macron', displayLabel: '¯' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'unmapped' },
        KeyQ: { type: 'text', output: 'Ξ' },
        KeyW: { type: 'text', output: '√' },
        KeyE: { type: 'text', output: 'Λ' },
        KeyR: { type: 'text', output: 'ℂ' },
        KeyT: { type: 'text', output: 'Ω' },
        KeyY: { type: 'text', output: '×' },
        KeyU: { type: 'text', output: 'Ψ' },
        KeyI: { type: 'text', output: 'Γ' },
        KeyO: { type: 'text', output: 'Φ' },
        KeyP: { type: 'text', output: 'ℚ' },
        BracketLeft: { type: 'text', output: 'ȷ' },
        BracketRight: { type: 'dead-key', deadKeyId: 'breve', displayLabel: '˘' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        KeyA: { type: 'text', output: '⊂' },
        KeyS: { type: 'text', output: '∫' },
        KeyD: { type: 'text', output: '∀' },
        KeyF: { type: 'text', output: '∃' },
        KeyG: { type: 'text', output: '∈' },
        KeyH: { type: 'text', output: 'Σ' },
        KeyJ: { type: 'text', output: 'ℕ' },
        KeyK: { type: 'text', output: 'ℝ' },
        KeyL: { type: 'text', output: '∂' },
        Semicolon: { type: 'text', output: 'Δ' },
        Quote: { type: 'text', output: '∇' },
        Backslash: { type: 'modifier', modifier: 'mod3', displayLabel: 'Mod3' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        KeyZ: { type: 'text', output: '∪' },
        KeyX: { type: 'text', output: '∩' },
        KeyC: { type: 'text', output: 'ℵ' },
        KeyV: { type: 'text', output: 'Π' },
        KeyB: { type: 'text', output: 'ℤ' },
        KeyN: { type: 'text', output: '⇐' },
        KeyM: { type: 'text', output: '⇔' },
        Comma: { type: 'text', output: '⇒' },
        Period: { type: 'text', output: '↦' },
        Slash: { type: 'text', output: 'Θ' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Narrow No-Break Space' },
        AltRight: { type: 'modifier', modifier: 'mod4', displayLabel: 'Mod4' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
  ],
}
