import type { KeyboardLayoutDefinition } from '../types'

/**
 * German PC ISO QWERTZ reference profile.
 *
 * Provenance:
 * - xkeyboard-config: symbols/de xkb_symbols "basic"
 * - Inherited latin definitions: symbols/latin xkb_symbols "type4" and "basic"
 * - Modifier definitions: level3(ralt_switch)
 *
 * Encodes standard German PC ISO layout (T1 according to DIN 2137-2) with Base,
 * Shift, and AltGraph (ISO Level 3) layers. Note that macOS Option mappings differ.
 */
export const DE_QWERTZ_LAYOUT: KeyboardLayoutDefinition = {
  id: 'de-qwertz',
  displayName: 'German QWERTZ',
  description: 'Standard German PC ISO keyboard layout (DIN 2137 T1).',
  provenance: 'xkeyboard-config symbols/de basic (including latin type4)',
  layers: [
    {
      layerNumber: 1,
      name: 'Base',
      description: 'Standard unshifted typing layer',
      modifiersDescription: 'None',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'dead-key', deadKeyId: 'circumflex', displayLabel: '^' },
        Digit1: { type: 'text', output: '1' },
        Digit2: { type: 'text', output: '2' },
        Digit3: { type: 'text', output: '3' },
        Digit4: { type: 'text', output: '4' },
        Digit5: { type: 'text', output: '5' },
        Digit6: { type: 'text', output: '6' },
        Digit7: { type: 'text', output: '7' },
        Digit8: { type: 'text', output: '8' },
        Digit9: { type: 'text', output: '9' },
        Digit0: { type: 'text', output: '0' },
        Minus: { type: 'text', output: 'ß' },
        Equal: { type: 'dead-key', deadKeyId: 'acute', displayLabel: '´' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        KeyQ: { type: 'text', output: 'q' },
        KeyW: { type: 'text', output: 'w' },
        KeyE: { type: 'text', output: 'e' },
        KeyR: { type: 'text', output: 'r' },
        KeyT: { type: 'text', output: 't' },
        KeyZ: { type: 'text', output: 'z' },
        KeyU: { type: 'text', output: 'u' },
        KeyI: { type: 'text', output: 'i' },
        KeyO: { type: 'text', output: 'o' },
        KeyP: { type: 'text', output: 'p' },
        BracketLeft: { type: 'text', output: 'ü' },
        BracketRight: { type: 'text', output: '+' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'caps-lock', displayLabel: 'Caps Lock' },
        KeyA: { type: 'text', output: 'a' },
        KeyS: { type: 'text', output: 's' },
        KeyD: { type: 'text', output: 'd' },
        KeyF: { type: 'text', output: 'f' },
        KeyG: { type: 'text', output: 'g' },
        KeyH: { type: 'text', output: 'h' },
        KeyJ: { type: 'text', output: 'j' },
        KeyK: { type: 'text', output: 'k' },
        KeyL: { type: 'text', output: 'l' },
        Semicolon: { type: 'text', output: 'ö' },
        Quote: { type: 'text', output: 'ä' },
        Backslash: { type: 'text', output: '#' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'text', output: '<' },
        KeyY: { type: 'text', output: 'y' },
        KeyX: { type: 'text', output: 'x' },
        KeyC: { type: 'text', output: 'c' },
        KeyV: { type: 'text', output: 'v' },
        KeyB: { type: 'text', output: 'b' },
        KeyN: { type: 'text', output: 'n' },
        KeyM: { type: 'text', output: 'm' },
        Comma: { type: 'text', output: ',' },
        Period: { type: 'text', output: '.' },
        Slash: { type: 'text', output: '-' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'altgr', displayLabel: 'AltGr' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 2,
      name: 'Shift',
      description: 'Uppercase and shifted symbol layer',
      modifiersDescription: 'Shift',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'text', output: '°' },
        Digit1: { type: 'text', output: '!' },
        Digit2: { type: 'text', output: '"' },
        Digit3: { type: 'text', output: '§' },
        Digit4: { type: 'text', output: '$' },
        Digit5: { type: 'text', output: '%' },
        Digit6: { type: 'text', output: '&' },
        Digit7: { type: 'text', output: '/' },
        Digit8: { type: 'text', output: '(' },
        Digit9: { type: 'text', output: ')' },
        Digit0: { type: 'text', output: '=' },
        Minus: { type: 'text', output: '?' },
        Equal: { type: 'dead-key', deadKeyId: 'grave', displayLabel: '`' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        KeyQ: { type: 'text', output: 'Q' },
        KeyW: { type: 'text', output: 'W' },
        KeyE: { type: 'text', output: 'E' },
        KeyR: { type: 'text', output: 'R' },
        KeyT: { type: 'text', output: 'T' },
        KeyZ: { type: 'text', output: 'Z' },
        KeyU: { type: 'text', output: 'U' },
        KeyI: { type: 'text', output: 'I' },
        KeyO: { type: 'text', output: 'O' },
        KeyP: { type: 'text', output: 'P' },
        BracketLeft: { type: 'text', output: 'Ü' },
        BracketRight: { type: 'text', output: '*' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'caps-lock', displayLabel: 'Caps Lock' },
        KeyA: { type: 'text', output: 'A' },
        KeyS: { type: 'text', output: 'S' },
        KeyD: { type: 'text', output: 'D' },
        KeyF: { type: 'text', output: 'F' },
        KeyG: { type: 'text', output: 'G' },
        KeyH: { type: 'text', output: 'H' },
        KeyJ: { type: 'text', output: 'J' },
        KeyK: { type: 'text', output: 'K' },
        KeyL: { type: 'text', output: 'L' },
        Semicolon: { type: 'text', output: 'Ö' },
        Quote: { type: 'text', output: 'Ä' },
        Backslash: { type: 'text', output: "'" },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'text', output: '>' },
        KeyY: { type: 'text', output: 'Y' },
        KeyX: { type: 'text', output: 'X' },
        KeyC: { type: 'text', output: 'C' },
        KeyV: { type: 'text', output: 'V' },
        KeyB: { type: 'text', output: 'B' },
        KeyN: { type: 'text', output: 'N' },
        KeyM: { type: 'text', output: 'M' },
        Comma: { type: 'text', output: ';' },
        Period: { type: 'text', output: ':' },
        Slash: { type: 'text', output: '_' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'altgr', displayLabel: 'AltGr' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
    {
      layerNumber: 3,
      name: 'AltGraph',
      description: 'Third level accessed via AltGr',
      modifiersDescription: 'AltGraph',
      mappings: {
        // Number row (Row E)
        Backquote: { type: 'text', output: '′' },
        Digit1: { type: 'text', output: '¹' },
        Digit2: { type: 'text', output: '²' },
        Digit3: { type: 'text', output: '³' },
        Digit4: { type: 'text', output: '¼' },
        Digit5: { type: 'text', output: '½' },
        Digit6: { type: 'text', output: '¬' },
        Digit7: { type: 'text', output: '{' },
        Digit8: { type: 'text', output: '[' },
        Digit9: { type: 'text', output: ']' },
        Digit0: { type: 'text', output: '}' },
        Minus: { type: 'text', output: '\\' },
        Equal: { type: 'dead-key', deadKeyId: 'cedilla', displayLabel: '¸' },
        Backspace: { type: 'action', action: 'backspace', displayLabel: 'Backspace' },

        // Upper row (Row D)
        Tab: { type: 'action', action: 'tab', displayLabel: 'Tab' },
        KeyQ: { type: 'text', output: '@' },
        KeyW: { type: 'text', output: 'ſ' },
        KeyE: { type: 'text', output: '€' },
        KeyR: { type: 'text', output: '¶' },
        KeyT: { type: 'text', output: 'ŧ' },
        KeyZ: { type: 'text', output: '←' },
        KeyU: { type: 'text', output: '↓' },
        KeyI: { type: 'text', output: '→' },
        KeyO: { type: 'text', output: 'ø' },
        KeyP: { type: 'text', output: 'þ' },
        BracketLeft: { type: 'dead-key', deadKeyId: 'diaeresis', displayLabel: '¨' },
        BracketRight: { type: 'text', output: '~' },

        // Home row (Row C)
        CapsLock: { type: 'modifier', modifier: 'caps-lock', displayLabel: 'Caps Lock' },
        KeyA: { type: 'text', output: 'æ' },
        KeyS: { type: 'text', output: 'ſ' },
        KeyD: { type: 'text', output: 'ð' },
        KeyF: { type: 'text', output: 'đ' },
        KeyG: { type: 'text', output: 'ŋ' },
        KeyH: { type: 'text', output: 'ħ' },
        KeyJ: { type: 'dead-key', deadKeyId: 'dot-below', displayLabel: '̣' },
        KeyK: { type: 'text', output: 'ĸ' },
        KeyL: { type: 'text', output: 'ł' },
        Semicolon: { type: 'dead-key', deadKeyId: 'double-acute', displayLabel: '˝' },
        Quote: { type: 'dead-key', deadKeyId: 'circumflex', displayLabel: '^' },
        Backslash: { type: 'text', output: '’' },
        Enter: { type: 'action', action: 'enter', displayLabel: 'Enter' },

        // Bottom row (Row B)
        ShiftLeft: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },
        IntlBackslash: { type: 'text', output: '|' },
        KeyY: { type: 'text', output: '»' },
        KeyX: { type: 'text', output: '«' },
        KeyC: { type: 'text', output: '¢' },
        KeyV: { type: 'text', output: '„' },
        KeyB: { type: 'text', output: '“' },
        KeyN: { type: 'text', output: '”' },
        KeyM: { type: 'text', output: 'µ' },
        Comma: { type: 'text', output: '·' },
        Period: { type: 'text', output: '…' },
        Slash: { type: 'text', output: '–' },
        ShiftRight: { type: 'modifier', modifier: 'shift', displayLabel: 'Shift' },

        // Modifier / Space row (Row A)
        ControlLeft: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
        AltLeft: { type: 'modifier', modifier: 'alt', displayLabel: 'Alt' },
        Space: { type: 'text', output: ' ', displayLabel: 'Space' },
        AltRight: { type: 'modifier', modifier: 'altgr', displayLabel: 'AltGr' },
        ControlRight: { type: 'modifier', modifier: 'ctrl', displayLabel: 'Ctrl' },
      },
    },
  ],
  modifierActivators: [
    { modifier: 'shift', physicalKeys: ['ShiftLeft', 'ShiftRight'], description: 'Shift' },
    { modifier: 'altgr', physicalKeys: ['AltRight'], description: 'AltGraph / Level 3 switch' },
    { modifier: 'caps-lock', physicalKeys: ['CapsLock'], description: 'Caps Lock' },
  ],
}
